services:
  bioinfo:
    build: .
    container_name: bioinfo-container
    volumes:
      - ./app:/app/
      - ./users:/users/
    ports:
      - "8000:8000"
      
    tty: true
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - main-net
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/bioinfo
      - PYTHONPATH=/app  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 3s
      timeout: 2s
      retries: 10

  ssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: ssh-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=bilbo123
      - USER_NAME=bilbo
    ports:
      - "0.0.0.0:2222:2222"
    volumes:
      - ssh_config:/config
    networks:
      - main-net
    depends_on:
      bioinfo:
        condition: service_healthy

  db:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bioinfo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main-net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - main-net

networks:
  main-net:
    driver: bridge

volumes:
  postgres_data:
  users:
  ssh_config:
